on:
    workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
      output_2: ${{ steps.gen_output.outputs.output_2 }}
      output_3: ${{ steps.gen_output.outputs.output_3 }}
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - name: Generate output
        id: gen_output
        run: |
          version="${{ matrix.version }}"
          echo "output_${version}=${version}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      # Will show
      # {
      #   "output_1": "1",
      #   "output_2": "2",
      #   "output_3": "3"
      # }
      - run: echo '${{ toJSON(needs.job1.outputs) }}'
      - name: Adding markdown
        run: echo '${{ toJSON(needs.job1.outputs) }}' >> $GITHUB_STEP_SUMMARY

  job3:
    runs-on: ubuntu-latest
    steps:
        - run: mkdir -p path/to/artifact
        - run: echo hello > path/to/artifact/world.txt
        - uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: path/to/artifact/world.txt

  job4:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: my-artifact
        - name: Display structure of downloaded files
          run: ls -R .
        - name: show file in workflow summary
          run: cat world.txt >> $GITHUB_STEP_SUMMARY




